### ISSUE TITLE
Deep copy for config file inheritance

### ISSUE THREAD

**Issue by m3brown** [cfpb/pantheon-helpers#16]
Currently the config options are split into two files - config and config_secret.  Config sources config_secret at the end of the file, so config_secret overrides any variables defined by config.

If an object with subvariables is defined in both files, the entire object in config is overridden.  For example:

config:

```
COUCHDB:
  HOST: 'localhost'
  PORT: 5984
```

config_secret:

```
COUCHDB:
  HOST: 'secrethost'
```

result:

```
COUCHDB:
  HOST: 'secrethost'
```

It'd be nice if a deep copy was available so that the object in config_secret could extend config.

For example:

result:

```
COUCHDB:
  HOST: 'secrethost'
  PORT: 5984
```

**Comment by dgreisen-cfpb** [comment]
done
